QuantEcon/QuantEcon.jl

src/mc_tools.jl, src/models/jv.jl
Two fixes:
* Changed `Dict` syntax in mc_tools
* Changed `::(Vector, (Vector, Vector))` to `::(Vector, Tuple{Vector, Vector})`
=> Makes QuantEcon.jl importable

src/Models.jl, src/distributions.jl, src/models/ifp.jl, test/runtests.jl, test/test_models.jl, test/test_quadsum.jl
Adds tests of all mutating methods from the `Models` sub-module.
Closes #38 
*NOTE* I had to disable the tests for the quadrature routines. In these tests we read in some data from a `.mat` data file (generated by matlab). There is some bug in `MAT.jl` that throws an error when we read in the data now. I don't have time to track this bug down and/or fix it, so I just disabled those tests for the time being.
=> Test mutating

examples/lq_permanent_1.jl, src/lqcontrol.jl, test/test_lqcontrol.jl
This PR adds support for a cross product term in the LQ dynamic programming problem, addressing #16.
Additionally:
* Cleaned up the linear algebra so that algorithms work natively with arrays and scalars without having to convert everything to `Array(T,1,1)` and use broadcast operators everywhere.
* Now `compute_sequence` returns a one dimensional array for scalar problems, and a two dimensional array for vector problems. 
Things to discuss:
* I have renamed the variable for the terminal period (in the finite horizon case) `T` to `term` since `T` is a very special name in the Julia universe, and nearly always used for a type variable. Is this okay?
* I renamed `Rf` to `rf` to cut down on the capital variables floating around, happy to revert this if it offends.
Things not in this PR:
* …
=> LQ Cross Product & Revamp

REQUIRE, src/QuantEcon.jl, src/mc_tools.jl
* Moved to LightGraphs for graph calculations
* New functions added
`recurrent_classes(mc::MarkovChain)`
`communication_classes(mc::MarkovChain)`
`is_irreducible(mc::MarkovChain)`
`period(mc::MarkovChain)`
Tests for these new functions are not included in this pull. I'm going to change up the tests file, so I'm submitting this pull and making those modifications separately, but all the old tests pass fine with the new code.
=> New features for mc_tools

src/lqcontrol.jl
@spencerlyon2 This is a small change to allow the lectures to compile the ``pdf`` file. The unicode character was causing compilation issues.
=> change unicode to ascii for latex parsing

src/QuantEcon.jl, src/random_mc.jl, test/runtests.jl, test/test_random_mc.jl
This is the Julia version of PR QuantEcon/QuantEcon.py#154.
I hope this will be useful when we conduct performance checks.
Examples:
```julia
julia> using QuantEcon
julia> mc = random_markov_chain(3)
Discrete Markov Chain
stochastic matrix:
3x3 Array{Float64,2}:
0.281188  0.61799   0.100822 
0.144461  0.848179  0.0073594
0.360115  0.323973  0.315912 
julia> mc = random_markov_chain(3, 2)
Discrete Markov Chain
stochastic matrix:
3x3 Array{Float64,2}:
0.369124  0.0       0.630876
0.519035  0.480965  0.0     
0.0       0.744614  0.255386
```
* Sparse matrix is not supported yet.
* Random seed is not supported: the main reason is that `StatsBase.sample` [[source](https://github.com/JuliaStats/StatsBase.jl/blob/master/src/sampling.jl)] seems not to accept an `rng` argument. I only have …
=> Random MarkovChain

src/random_mc.jl, test/test_random_mc.jl
For `k=1`, `probvec` (and hence `random_stochastic_matrix` and `random_markov_chain`) raises an error with version 0.4, due to the change in the behavior of `sort`.
Version 0.4.1:
```julia
julia> k, m = 1, 3;
julia> r = rand(k-1, m)
0x3 Array{Float64,2}
julia> sort(r, 1)
ERROR: ArgumentError: step cannot be zero
in steprange_last at /Applications/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib
in sort_chunks! at sort.jl:495
in sort at sort.jl:489
```
Version 0.3.11:
```julia
julia> k, m = 1, 3;
julia> r = rand(k-1, m)
0x3 Array{Float64,2}
julia> sort(r, 1)
0x3 Array{Float64,2}
```
Fix by handling the case of `k=1` separately.
=> BUG: Fix bug in probvec

src/QuantEcon.jl, src/random_mc.jl, test/test_random_mc.jl
Usage:
```julia
julia> using QuantEcon
julia> num_states, num_actions = 3, 2;
julia> beta = 0.95;
julia> ddp = random_discrete_dp(num_states, num_actions, beta)
QuantEcon.DiscreteDP{Float64,3,2,Float64}(3x2 Array{Float64,2}:
3.18123   -0.22298 
-1.02028    0.312704
-0.239984   2.46322 ,3x2x3 Array{Float64,3}:
[:, :, 1] =
0.451384  0.0960853
0.333482  0.444263 
0.21166   0.184576 
[:, :, 2] =
0.392036  0.43661 
0.337597  0.250181
0.249018  0.287269
[:, :, 3] =
0.15658   0.467305
0.328921  0.305556
0.539322  0.528154,0.95)
julia> res = solve(ddp);
julia> res.num_iter
220
julia> res.v
3-element Array{Float64,1}:
42.0335
39.4174
41.3262
julia> res.sigma
3-element Array{Int64,1}:
1
5
6
```
=> Add random_discrete_dp

src/markov/ddp.jl
Replaces #85. This is even faster (except for small-size arrays) and simpler.
* [`reduce_last2`](http://nbviewer.jupyter.org/gist/oyamad/75c9630268278d8d54c8/reduce_last_jl02.ipynb)
The speed of `solve` is more or less the same or slightly faster.
* [this version](http://nbviewer.jupyter.org/gist/oyamad/c161449d73a620d53ff8/random_ddp_jl03.ipynb)
=> ddp: Re-implement 3-dim matrix * vector with reshape

src/markov/ddp.jl, src/util.jl, test/test_ddp.jl
Changes the types of the function arguments in `meshgrid` from `Vector` to `AbstractVector`.
=> Change type in meshgrid function

src/mc_tools.jl, test/test_mc_tools.jl
1.
This is to propose matching the `simulate` method with that in the Python version (see https://github.com/QuantEcon/QuantEcon.py/issues/146#issuecomment-135328616). It works as follows:
```julia
julia> using QuantEcon
julia> mc = MarkovChain([0.4 0.6; 0.2 0.8])
Discrete Markov Chain
stochastic matrix:
2x2 Array{Float64,2}:
0.4  0.6
0.2  0.8
julia> simulate(mc, 5)
5-element Array{Int64,1}:
2
2
1
1
2
julia> simulate(mc, 5, [1, 2])
5x2 Array{Int64,2}:
1  2
1  1
2  1
2  1
2  2
julia> simulate(mc, 5, num_reps=3)
5x3 Array{Int64,2}:
1  2  2
2  1  1
2  2  1
1  2  2
1  1  1
julia> simulate(mc, 5, 1, num_reps=3)
5x3 Array{Int64,2}:
1  1  1
1  1  2
2  2  2
2  2  2
1  2  2
julia> simulate(mc, 5, [1, 2], num_reps=3)
5x6 Array{Int64,2}:
1  2  1  2  1  2
2  2  1  1  2  1
2  1  2  2  1  2
2  2  1  2 …
```
=> MarkovChain simulate: Match with python version

test/runtests.jl
@spencerlyon2 this isn't needed anymore in the tests as it isn't used
=> don't need to include compat in tests anymore

src/QuantEcon.jl, src/quad.jl, src/util.jl, test/test_quad.jl, test/test_util.jl
Minor PR to implement a faster version of `gridmake` as well as implement a mutating version.
Also added some tests.
NOTE: this is breaking because previously we had the first array varying the fastest, now we have the last array varying the fastest. I don't believe this should cause problems for anyone, but if it does let me know and we'll do the other implementation.
- - -
A quick benchmark comparison:
```
julia> a1, a2, a3 = randn(10), randn(10), randn(10);
julia> @benchmark gridmake1(a1, a2, a3)
Benchmarks.ExecutionResults:
samples:                          (see :samples field)
precompiled?:                     true
multiple evaluations per sample?: false
total time spent benchmarking:    0.48 s
Benchmarks.SummaryStats:
estimated time per evaluation: 4.25 ms [3.34 ms, 5.17 ms]
R² of …
```
=> Implement faster gridmake

src/util.jl, test/test_quad.jl, test/test_util.jl
- Also re-instated multi-dim quad tests
In #104 I implemented a faster version of gridmake, but it swapped the assumption about whether the first or last column moves the fastest. Turns out this was not innocuous in some places where I am using `gridmake`, so this PR implements an efficient version of `gridmake`, but restores the original behavior that the first variable varies the fastest.
=> Fix gridmake ordering, add docstrings to util.jl closes #106

src/QuantEcon.jl
* delete evaluate_policy!  : which doesn't exist in ddp.jl
* export num_states  : for convenience
=> Modify src/QuantEcon.jl

src/markov/ddp.jl
Matrix-vector multiplication is carried out first, instead of matrix-matrix multiplication. This cuts the number of memory allocations and runtime.
=> Fixed Matrix Multiplication in DDP

src/lqcontrol.jl
I fixed the type inconsistency and I also changed a few words in the comments at the end to be consistent with the fact that `w_path`, in the original code (not following my changes), is not a vector of `N(0,1)` innovations but it's stored as `C*N(0,1)` vector. This is still somewhat different than how it's described in the initial documentation, as there it's said that `w` is `N(0,1)`
=> Fixing bug related to w_path and some related comments

src/QuantEcon.jl, src/markov/mc_tools.jl, test/test_mc_tools.jl
1.
This is to add `stationary_distributions` for `MarkovChain`, which always returns stationary distributions as a Vector of Vectors (even when there is a unique stationary distribution), as in the Python version (EDIT: in the sense that the Python version does not change the dimension of output array regardless of the number of stationary distributions). This avoids first the type-instability and second the issue of whether to contain distributions as rows or columns when the return is a Matrix.
The current `mc_compute_stationary` returns a Vector when there is a unique recurrent class, and returns a Matrix when there are more than one.
2.
I need a help regarding the best way to determine the eltype of the output vectors. Consider a `MarkovChain{Int64}` with the stochastic matrix
```jl …
```
=> Add `stationary_distributions`

src/lqcontrol.jl, src/markov/ddp.jl
This commit fixes the overwriting of `s_indices` (and `a_indices`) when sorting, which prevented re-use of the same vectors. See #117
=> Fix indices overwr ddp

src/markov/mc_tools.jl
With num_reps > 1 the t+1 draw of the chain was always using the distribution conditional on the value at t for the first repetition.
=> bug fix in Markov chain simulation

REQUIRE
also add StatsBase explicitly to REQUIRE, on the off-chance it's ever not available
as an indirect dependency
=> add minimum version requirement for Compat.view

src/matrix_eqn.jl
When fixing the notebook `lqcontrol_solutions_jl` I encountered a situation where matrix `Z` on this line https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/matrix_eqn.jl#L116 is actually an `Array{Float64, 1}` with a single element (as `R` is a scalar). As `Base.cond` requires a matrix, this commit makes `Z` into a comformable `Array{Float64, 2}` always.
=> Upgraded code to handle 1 dimensional cases

src/QuantEcon.jl, src/markov/mc_tools.jl, test/test_mc_tools.jl
In reference to #119. There are now four simulation methods that do the following:
* `simulate`: simulates one sample path of the Markov chain and returns a `Vector`
* `simulate!`: fills a pre-allocated `Matrix` with one simulation of the chain down each column
* `simulate_indices` and `simulate_indices!`: same as above, except they return sample paths with the indices of the state values as elements
I implemented @spencerlyon2's idea about initial conditions. The initial conditions can either be blank, a scalar, or a vector, with implications for each described in the docstrings or [here](https://github.com/QuantEcon/QuantEcon.jl/issues/119#issuecomment-238163616).
=> Redesign of the MarkovChain simulation methods

src/compute_fp.jl
If we look in [this notebook](http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.applications/blob/master/optgrowth/optgrowth_solutions_jl.ipynb) we see the warning
```
WARNING: max_iter exceeded in compute_fixed_point
```
It's a bit out of place because we deliberately set `max_iter`.  I can't think of a good fix so I just changed `exceeded` to `attained`.
=> Minor issue with warnings

src/compute_fp.jl
Example:
```
julia> f(x) = 0.5 * x
WARNING: Method definition f(Any) in module Main at REPL[14]:1 overwritten at REPL[22]:1.
f (generic function with 1 method)
julia> compute_fixed_point(f, 1.0, verbose=0)
6.103515625e-5
julia> compute_fixed_point(f, 1.0, verbose=1)
6.103515625e-5
julia> compute_fixed_point(f, 1.0, verbose=2)
Compute iterate 10 with error 0.0009765625
Converged in 14 steps
6.103515625e-5
julia> compute_fixed_point(f, 1.0, verbose=1, max_iter=5)
WARNING: max_iter attained in compute_fixed_point
0.03125
julia> compute_fixed_point(f, 1.0, verbose=0, max_iter=5)
0.03125
julia> compute_fixed_point(f, 1.0, verbose=10)
ERROR: ArgumentError: verbose should be 0, 1 or 2
in #compute_fixed_point#3(::Float64, ::Int64, ::Int64, ::Int64, ::Function, ::#f, ::Float64) at …
```
=> edited warnings

.travis.yml, src/QuantEcon.jl, src/markov/mc_tools.jl, test/test_mc_tools.jl
This PR revamps the internals behind `simulate` and `simulate_indices` to use the Julia iterator protocol.
The current API for `simulate`, `simulate!`, `simulate_indices`, `simulate_indices!` has not changed. 
However, we can now do things more flexibly.  I have defined two new types `MCIndSimulator` and `MCSimulator` that are responsible for _iterating_ over the simulation of a MarkovChain. This enables us to do things like
```julia
mcs = MCSimulator(mc, 200, 1)
sim1 = collect(mcs)
sim2 = collect(mcs)
for i in mcs
do_something_cool(i)
end
```
You can see the new (and greatly simplified!!) implementation of `simulate!` and `simulate_indices!` for other ideas about what is possible.
=> ENH: added iterators for MarkovChain simulation

src/sampler.jl, test/test_sampler.jl
I found my code contained a bug...
```jl
n = 2
mu = zeros(n)
Sigma = eye(Int, n)
MVNSampler(mu, Sigma)
```
```
ERROR: ArgumentError: generic pivoted Cholesky factorization is not implemented yet
in QuantEcon.MVNSampler{TM<:Real,TS<:Real,TQ<:Union{Float32,Float64}}(::Array{Float64,1}, ::Array{Int64,2}) at /Users/oyama/.julia/v0.5/QuantEcon/src/sampler.jl:26
```
=> BUG: Fix MVNSampler

.travis.yml, src/interp.jl, test/test_interp.jl
This extends LinInterp to work for more than one function at a time.
If you pass an `AbstractVector` and an `AbstractMatrix`, each column of the matrix will be treated as another function to which the interpolation is applied.
=> ENH: LinInterp for mulitple functions

src/QuantEcon.jl, src/markov/markov_approx.jl, test/test_markov_approx.jl
Threw this together for kicks and giggles last night (it was a 15 minute exercise) in response to the [discourse thread](http://discourse.quantecon.org/t/estimate-markovchain-from-data-using-ml/239/2) by @jstac 
Uses maximum likelihood estimation to get transition matrix for a discrete number of states.
Attn: @jstac @sglyon
=> Discrete Markov chain estimation

docs/make.jl, mkdocs.yml, src/arma.jl
Hi @sglyon, this should add support for latex in Documenter.jl
Would you and @mmcky be able to test this?
@mmcky can you see if there is an equivalent of readthedocs to trigger a build of this branch of the documentation
Info is here: https://juliadocs.github.io/Documenter.jl/v0.1.3/
arma.jl docstring has been edited for testing
=> add latex support to documenter

src/arma.jl, src/compute_fp.jl, src/discrete_rv.jl, src/estspec.jl, src/interp.jl, src/kalman.jl, src/lae.jl, src/lqcontrol.jl, src/lqnash.jl, src/lss.jl, src/markov/ddp.jl, src/markov/markov_approx.jl, src/markov/mc_tools.jl, src/markov/random_mc.jl, src/matrix_eqn.jl, src/quad.jl, src/quadsums.jl, src/robustlq.jl, src/zeros.jl
Yay it's pretty now
* added latex rendering to all docs
* updated links to lectures.quantecon.org
* tried to be more consistent with variable/value highlighting
* a lot of indenting to fix alignment of lists
@cc7768 Sorry I un-did all your unicode work but it wasn't displaying properly on my computer! Could you check the documentation now - I had to guess some of the notation. To build the docs, type `julia docs/make.jl` and open `docs/build/index.html`
* I think the structure/layout of the docs should be cleaned up - it's hard to navigate at the moment (although I don't know how to do this)
* I think this reference `scipy/scipy/optimize/Zeros/bisect.c` is outdated - might be worth linking [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) now
* …
=> Latex rendering in docs + other improvements

REQUIRE
This PR should close #169 
- `Optim` needs to be v0.7.3 or more to use `Optim.Options` [here](https://github.com/QuantEcon/QuantEcon.jl/blob/master/src/markov/markov_approx.jl#L617). (See [Optim v0.7.3 release notes](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/NEWS.md#optim-v073-release-notes))
- `NLopt` itself requres at least v0.3.4 to avoid [`Uint8` in v0.3.3](https://github.com/JuliaOpt/NLopt.jl/blob/v0.3.3/src/NLopt.jl#L389). ([`UInt8` in v0.3.4](https://github.com/JuliaOpt/NLopt.jl/blob/v0.3.4/src/NLopt.jl#L389))
=> Add minimum version for Optim and NLopt

src/optimization.jl
This adds documentation to the `golden_method` function.
Currently only adds for version with scalar bounds -- Will add docs to vector version as well once I make sure I understand what it does.
I will ping @sglyon once this is done.
=> WIP: Add short doc on golden_method

src/QuantEcon.jl, src/modeltools/utility.jl, test/runtests.jl, test/test_modeltool.jl
In this pull request, I introduce an abstract type `AbstractUtility`. I also include 4 concrete utility functions and their derivatives: `LogUtility`, `CRRAUtility`, `CFEUtility`, and `EllipticalUtility` -- The first two are typically used in modeling consumption utility and second two for labor utility.
Additionally, the folder `modeltools` can be a placeholder for adding things like production functions etc... in the future.
Example
```julia
using QuantEcon
u = LogUtility()
@show u(1.0)
@show derivative(u, 1.0)
```
@sglyon
=> Model tools: Add various utility functions

src/QuantEcon.jl, src/util.jl, test/runtests.jl, test/test_util.jl
Based on the QuantEcon.py code from https://github.com/QuantEcon/QuantEcon.py/pull/344
Also would close https://github.com/QuantEcon/QuantEcon.jl/issues/178
=> ENH: Add simplex tools

src/matrix_eqn.jl, test/test_matrix_eqn.jl
The same changes as in the Python side:
1. QuantEcon/QuantEcon.py#364
2. QuantEcon/QuantEcon.py#361
=> FIX: Remove 0.0 from `candidates` in `solve_discrete_riccati`

src/modeltools/utility.jl, test/test_modeltool.jl
The utility functions were using `ifelse` to evaluate in places where the utility function couldn't be evaluated -- This doesn't work because it evaluates both cases at once and it throws an error.
This is WIP and still needs some tests to check this and potentially some other cases.
For example
```
u = LogUtility()
u(-0.01) 
```
=> WIP: Fix utility functions to branch

src/QuantEcon.jl, src/modeltools/types.jl, test/test_modeltool.jl
I'd like to get some feedback on the inclusion of this macro here.
The docstring (especially the example) and tests should describe what it does pretty well.
My main question for the team is "do we want something like this in here?" I found that for many models I work on, I end up writing an `Observation` type to hold a single observation of state/control/auxiliary variables and then I end up writing a `Simulation` type that holds arrays of those variables and calling `getindex` on the `Simulation` will return an `Observation`. This macro automates the creation of the `Simulation` type and a handful of useful methods defined on that type.
Opinions welcome/accepted/encouraged
=> ENH: added `@def_sim` macro that I use in a few research projects

src/QuantEcon.jl, src/ecdf.jl, test/test_ecdf.jl
=> QuantEcon.ecdf calls StatsBase.ecdf

src/QuantEcon.jl, src/util.jl, test/test_util.jl
Add `next_k_array!` and `k_array_rank` utilities, mimicking the [counterpart Python version](https://github.com/QuantEcon/QuantEcon.py/blob/e61702fd6622ae046d8252b38ab101454c2e74b2/quantecon/util/combinatorics.py#L12) implemented by @oyamad. It is mainly copying and pasting, and modifying a little part (let index start from 1 rather than 0).
=> Add `next_k_array!` and `k_array_rank`.

src/QuantEcon.jl, src/quad.jl
This is a request for comments (RFC) on a new approach for constructing quadrature weights and nodes for any continuous, univariate distribution.
The algorithm, some properties, and even an example of intended usage is written down in the docstring for `qnwdist`. 
What thoughts does the team have about this approach? Can anyone think of a potentially better heuristic for choosing the nodes (besides the two I've implemented here).
Before merging I will write up some tests. My idea for testing would be to take a known function `f` and compare `dot(f.(nodes), weights)` to `quadgk(x -> f(x) pdf(d, x), support(d)...)` and see if our crude approximation gets close to the (hopefully accurate) adaptive Gauss Kronrod implementation  in quadgk for approximating `E[f(x) | x ~ d]`
cc …
=> RFC: Sl/qnwdist

src/markov/ddp.jl
=> Drop `num_actions` from DiscreteDP

.travis.yml, REQUIRE, src/QuantEcon.jl, src/discrete_rv.jl, src/markov/ddp.jl, src/modeltools/utility.jl, src/sampler.jl, src/util.jl, test/REQUIRE, test/util.jl
Enables `using QuantEcon` in v0.7 (some tests do not pass though).
=> Fix 0.7 errors (for using QuantEcon)

src/sampler.jl
To have `MVNSampler` work in v0.7 by avoiding `RankDeficientException` (used in `Games.jl`).
=> COMPAT: Use cholesky for cholfact

README.md
Is this descriptive enough? Should we keep installation instructions for sub-1.0?
=> Update installation for Julia 1.0

src/kalman.jl
There need to be some dots added. These are the two that I encountered. It might be necessary somwhere else as well.
Example:
```
using QuantEcon
A = [0. 0.; 0. 1]
G = [1. 0.5]
R = 0.
Q = [1 0.; 0. 1]
k = Kalman(A,G,Q,R)
stationary_values(k)
prior_to_filtered!(k, 1.)
```
=> Kalman Filter: Fix problem when y is a scalar but x is a vector

.travis.yml, docs/Project.toml, docs/make.jl, src/util.jl
closes #239.
Update keyword value for `Documenter.makedocs` and set `prettyurls` off as in QuantEcon/Games.jl#106.
It seems that we cannot break a math expression in `@doc` block if we use "$$", as I modified in `util.jl`. Otherwise it will trigger documentation rendering failure.
=> DOC: Update

src/markov/random_mc.jl, test/test_random_mc.jl
Fix the bug:
```jl
QuantEcon.random_probvec(5)
```
```
UndefVarError: rng not defined
```
=> Fix bug in random_probvec

src/markov/markov_approx.jl
A long time ago I asked whether `tauchen` should limit `n_std` to being an `Integer`:
https://discourse.quantecon.org/t/integer-n-std-in-tauchen/541
I don't think there should be such restriction. This PR relaxes `n_std` to be a subtype of `Real`.
=> allowed `tauchen` to take non-integer `n_std` positional argument

test/test_markov_approx.jl
This is a quick and dirty fix for #273. Ideally one would use stable RNGs in the tests. But that is beyond my capacities.
=> Fix broken test on julia 1.7+

src/markov/markov_approx.jl
- Default value wasn't properly set. 
- `N` was not defined. 
- `Tbar` was not defined (though `TBar` was defined).
- I set initial value more explicitly by using `length(D)`
- I renamed `TBar` into `Tbar`. I think it's better as a variable that represents $\overline{T}$.
=> fix default value and change variable name of discrete_approximation

src/sampler.jl
```
┌ Warning: `cholesky(A::Union{StridedMatrix, RealHermSymComplexHerm{<:Real, <:StridedMatrix}}, ::Val{true}; tol = 0.0, check::Bool = true)` is deprecated, use `cholesky(A, RowMaximum(); tol, check)` instead.
│   caller = ip:0x0
└ @ Core :-1
```
=> MAINT: Fix deprecation warning on `cholesky`

README.md
Copyright is out of date and should not be attributed to us.
=> Removed names of Spencer, John and Tom from README, small updates

README.md
Switch from `coveralls` to `codecov`: the former seems no longer working.
=> MAINT: Update coverage badge

src/markov/markov_approx.jl
Just noticed this extra line that isn't used.
=> Remove reduntant line in rouwenhorst()

.github/workflows/ci.yml
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> CI: Update `actions/cache`
