QuantEcon/QuantEcon.jl

REQUIRE
src/mc_tools.jl
test/test_mc_tools.jl

To support new functions, and clean up some old stuff.

Update MarkovChain Tests

---

src/mc_tools.jl
test/test_mc_tools.jl

BUG: Fix a bug in mc_tools 2

---

src/random_mc.jl

Corresponding to QuantEcon/QuantEcon.py#184

random_probvec: Remove temporary array

---

examples/finite_dp_og_example.jl
src/QuantEcon.jl
src/markov/ddp.jl
test/runtests.jl
test/test_ddp.jl

**Status:** Not Ready to be Merged, Open for Review
Add Discrete DP
- value iteration
- policy function iteration 
- modified policy function iteration
Outstanding items
I will submit an associated PR for the QuantEcon website to add ``julia`` lecture

Add Discrete DP

---

test/REQUIRE
test/runtests.jl
test/test_arma.jl
test/test_compute_fp.jl
test/test_ddp.jl
test/test_discrete_rv.jl
test/test_ecdf.jl
test/test_estspec.jl
test/test_kalman.jl
test/test_lae.jl
test/test_lqcontrol.jl
test/test_lqnash.jl
test/test_lss.jl
test/test_markov_approx.jl
test/test_matrix_eqn.jl
test/test_mc_tools.jl
test/test_quad.jl
test/test_quadsum.jl
test/test_random_mc.jl
test/test_robustlq.jl

update tests to use BaseTestNext instead of FactCheck Fixes #89

---

REQUIRE
src/QuantEcon.jl

This fixes a precompile error on julia 0.5 and should also work on 0.4.

Use Primes package

---

src/lqcontrol.jl

This fixes the existing code, as policies are solved for backwards and are used forwards in the solution iteration

Fill in policies backwards

---

src/matrix_eqn.jl

This addresses issue #134 as discussed in the comments

Relaxed getZ type

---

.travis.yml
src/arma.jl

This allows installing the package elsewhere.
Add testing against 0.5 to Travis - this runs the most
recent RC now, release once final tags are done

Use dirname(@__FILE__) instead of Pkg.dir

---

.travis.yml
src/quad.jl
test/test_quad.jl

ENH: make quad routines type stable

---

.travis.yml

if you don't support 0.4 any more, you need to update REQUIRE accordingly

add back 0..4 testing

---

src/QuantEcon.jl
src/interp.jl
test/runtests.jl
test/test_interp.jl

ENH: add linear interpolation routine

---

src/discrete_rv.jl
src/markov/mc_tools.jl
test/test_discrete_rv.jl

ENH: use rand instead of draw for drv sampling 

---

src/arma.jl

* This PR adds latex rendering to `arma.jl`

add latex rendering in arma.jl

---

.travis.yml

- hdf5-tools for MAT.jl based tests
- liblinopt for NLopt

TEST: update travis to install apt deps

---

src/compute_fp.jl

Remove warning message when converged with max_iter

---

test/test_lae.jl

I fixed the deprecation warning in `test_lae.jl`.

Fixed issue #200.

---

src/quad.jl

Changed diagm() to Matrix(Diagonal())

Changing diagm to Matrix(Diagonal()) in qnwnorm()

---

src/kalman.jl

A small fix to make the link work again.

Fix link to Kalman-Lecture

---

src/QuantEcon.jl
src/quad.jl

lgamma from "SpecialFunctions" is depracated. Updated to (logabsgamma(x))[1]

qnwbeta: lgamma updated to logabsgamma  

---

src/util.jl

Fix, in particular, [this](https://quantecon.github.io/QuantEcon.jl/v0.14/api/QuantEcon.html#QuantEcon.simplex_grid-Tuple{Any,Any}).

DOC: Fix/update docstrings in util.jl

---

src/QuantEcon.jl
src/util.jl
test/test_util.jl

Possibly used in `GameTheory.jl`
```julia
julia> sg = SimplexGrid(3, 4);
julia> for x in sg
@show x
end
x = [0, 0, 4]
x = [0, 1, 3]
x = [0, 2, 2]
x = [0, 3, 1]
x = [0, 4, 0]
x = [1, 0, 3]
x = [1, 1, 2]
x = [1, 2, 1]
x = [1, 3, 0]
x = [2, 0, 2]
x = [2, 1, 1]
x = [2, 2, 0]
x = [3, 0, 1]
x = [3, 1, 0]
x = [4, 0, 0]
```

ENH: Add iterator version `simplex_grid`

---

docs/make.jl

FIX: DOC: Set `size_threshold` to `nothing`

---

src/markov/ddp.jl
src/markov/random_mc.jl
test/test_ddp.jl
test/test_random_mc.jl

FIX: Fix bugs around `DiscreteDP`

---

.github/workflows/ci.yml

Implementing suggestions by ChatGPT...

CI: Update ci.yml
